version: "3.0"

services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: "$DB_PASSWORD"
            POSTGRES_USER: admin
            POSTGRES_DB: ipfs-pinner
        ports:
            - 5432:5432

    adminer:
        image: adminer:latest
        ports:
            - 8080:8080


