apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ipfs-pinner-frontend
  labels:
    app: {{ .Release.Name }}-ipfs-pinner-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ipfs-pinner-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ipfs-pinner-frontend
    spec:
      containers:
      - name: ipfs-pinner-frontend
        image: ghcr.io/atomgenie/ipfs-pinner-front:{{ .Values.imageVersion }}
        ports:
        - containerPort: 8080
        env:
        - name: BACK_URL
          value: http://{{ .Release.Name }}-ipfs-pinner-back-service.{{ .Release.Namespace }}.svc.cluster.local:8090

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ipfs-pinner-front-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-ipfs-pinner-frontend

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-ipfs-pinner-front-virtual-service
spec:
  hosts:
  - ipfs-pinner.k3s.tamtanguy.fr
  gateways:
  - tls-gateway
  http:
  - name: "backend"
    route:
    - destination:
        host: {{ .Release.Name }}-ipfs-pinner-front-service.{{ .Release.Namespace }}.svc.cluster.local
