apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-ipfs-pinner-postgres-virtual-service
spec:
  hosts:
  - {{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local
  http:
  - name: "database"
    route:
    - destination:
        host: {{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local
