apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-password
type: Opaque
data:
  value: {{ .Values.postgresql.global.postgresql.postgresqlPassword | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-token
type: Opaque
data:
  value: {{ .Values.token | b64enc }}
