name: IPFS-Pinner-Front

on:
  push:
    tags:
        - "**"

jobs:
  build:
    name: IPFS Pinner Front
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_SECRET }}
          registry: ghcr.io
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: infra/dockerfiles/front/Dockerfile
          tags: ghcr.io/atomgenie/ipfs-pinner-front:${{steps.vars.outputs.tag}}
          context: .
